<footer>
    <hr/>
    <div class="footer">
        <p >&copy; 成都普联众通科技有限公司 2013</p>
    </div>
</footer>
<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/scrolltotop.js"></script>
<script type="text/javascript">
    jQuery(function($){
        $.scrolltotop({
        className: 'totop',
        controlHTML : '<a href="javascript:;">回到顶部↑</a>',
        offsety:0
       });
    });
</script>