<?php
    //Menu Db
    define('MENU_DB', '../../db/dish.db3');
    
    define('CATEGORIES', "category");
    define('UNITS', 'unit');
    define("DISHES", 'dishInfo');
    define("DISH_CATEGORY", "dishCategory");
    define("PRINTERS", 'sortPrint');
    

    //User Info Database
    define('USER_DB', "../../db/user.db3");
    
    define('USER_INFO',"userInfo");
    define('USER_ID', "id");
    define('USER_NAME',"username");
    define('USER_PWD',"password");
    define('USER_PERMISSION',"permission"); 
    
    //info db(talbe info & services info)
    define('INFO_DB', "../../db/temporary/orderInfo.db3");
    
    define('TABLE_INFO', "tableInfo");
    define('TABLE_NAME', "tableName");
    define('TABLE_ID', "id");
    define('TABLE_STATUS', "status");
    define('TABLE_CATEGORY',"tableCategory");
    define('TABLE_INDEX',"tableOrder");
    define('TABLE_AREA',"tableArea");
    define('TABLE_FLOOR',"tableFloor");
    
    define('NOTIFICATION_TYPE_COLUM_VALUE', 'serviceName');
    
    define('SERVICES', "serviceList");
    
    define('TABLE', "tableInfo");
    
    //user data
    define('IMG_UPLOAD_PATH', '../../user_data/tmp/');
    define('IMG_PATH', '../../user_data/img/');
    
    
    //
?>